<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>SaludCORE | Registro</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/dist/css/AdminLTE.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/plugins/iCheck/square/blue.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
       <script src="<?php echo $this->baseUrl; ?>/js/usuario.js"></script>
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <div class="login-logo">
                <b>Salud</b>CORE
            </div>
            <!-- /.login-logo -->
            <div class="login-box-body">
                <p class="login-box-msg">Crear una nueva cuenta</p>
                
                    <div class="form-group has-feedback">
                        <input type="text" class="form-control" name="new_user" id="new_user" placeholder="Usuario" autocomplete="off">
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input type="email" class="form-control" name="new_email" id="new_email" placeholder="Correo electronico" autocomplete="off">
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" name="new_clave" id="new_clave"  placeholder="Contraseña" autocomplete="off">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" name="new_clave2" id="new_clave2"  placeholder="Repita la Contraseña" autocomplete="off">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div id="vacio" >
                            </div>  
                            <div id="clave_igual" >
                            </div>
                            <div id="acuerdo_" >
                            </div>
                            <div id="correo_valido" >
                            </div>
                            </div> 
                        </div>
                    <div class="row">
                        <div class="col-xs-8">
                            <div class="checkbox icheck">
                                <label>
                                    <input type="checkbox" id="acuerdo" name="acuerdo"> Estoy de acuerdo con los terminos de servicio
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat" onclick="agregarUsuario()">Registrarse</button>
                        </div>
                        
                        <!-- /.col -->
                     </div>
                <!-- /.social-auth-links -->

                Ya posee una cuenta?<a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'index')); ?>" class="text-center">Clic aqui</a>

            
            <!-- /.login-box-body -->
        </div>
        <!-- /.login-box -->
</div>
        <!-- jQuery 3 -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- iCheck -->
        <script src="<?php echo $this->baseUrl; ?>/plugins/iCheck/icheck.min.js"></script>
        
        <script>
            $(function() {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' /* optional */
                });
            });
        </script>
        <input type="hidden" name="dir" id="dir" readonly="readonly"  value="<?php echo $this->baseUrl; ?>">
    </body>
</html>