<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>AdminLTE 2 | Dashboard</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/Ionicons/css/ionicons.min.css">
        <!-- DataTables -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/dist/css/skins/_all-skins.min.css">
        <!-- Morris chart -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/morris.js/morris.css">
        <!-- jvectormap -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/jvectormap/jquery-jvectormap.css">
        <!-- Date Picker -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
        <!-- Daterange picker -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/bower_components/bootstrap-daterangepicker/daterangepicker.css">
        <!-- bootstrap wysihtml5 - text editor -->
        <link rel="stylesheet" href="<?php echo $this->baseUrl; ?>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

        <!-- ./wrapper -->

        
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper ">

            <header class="main-header">
                <!-- Logo -->
                <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>S</b>C</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Salud</b>CORE</span>
                </a>
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Messages: style can be found in dropdown.less-->

                            <!-- Notifications: style can be found in dropdown.less -->

                            <!-- Tasks: style can be found in dropdown.less -->

                            <!-- User Account: style can be found in dropdown.less -->

                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                     <!--<img src="<?php echo $this->baseUrl; ?>/dist/img/avatar5.png" class="user-image" alt="User Image">
                                    -->
                                    <i class="fa fa-user-circle " >
                                        
                                    </i>
                                    <span class="hidden-xs">
                                        <?php if($this->user) :  
                                            echo $this->escape($this->user->usuario);
                                        endif; ?>
                                    </span>
                                     
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <!--<img src="<?php echo $this->baseUrl; ?>/dist/img/avatar5.png" class="img-circle" alt="User Image">
                                        -->
                                        <i class="fa fa-user-circle fa-5x" ></i>
                                        <p>
                                            <?php if($this->user) :  
                                            echo $this->escape($this->user->usuario);?>
                                         - Actividad
                                            <small>Miembro desde: <?php echo $this->escape($this->user->fecha_creacion);?></small>
                                            <?php endif; ?>
                                        </p>
                                    </li>
                                    <!-- Menu Body 
                                    <li class="user-body">
                                        <div class="row">
                                            <div class="col-xs-4 text-center">
                                                <a href="#">Followers</a>
                                            </div>
                                            <div class="col-xs-4 text-center">
                                                <a href="#">Sales</a>
                                            </div>
                                            <div class="col-xs-4 text-center">
                                                <a href="#">Friends</a>
                                            </div>
                                        </div>
                                        <!-- /.row 
                                    </li>-->
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat"><i class="fa fa-user-circle"></i>&nbsp;&nbsp;&nbsp;Perfil</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout')); ?>" 
                                               class="btn btn-default btn-flat">Salir&nbsp;&nbsp;&nbsp;<i class="fa fa-sign-out"></i></a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            
                            <!-- Control Sidebar Toggle Button 
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>-->
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <i class="fa fa-user-circle fa-3x" ></i>
                             <!--<img src="<?php echo $this->baseUrl; ?>/dist/img/avatar5.png" class="img-circle" alt="User Image">
                        -->
                             </div>
                        <div class="pull-left info">
                            <p>
                                <?php if($this->user) :  
                                            echo $this->escape($this->user->usuario);
                                        endif; ?>
                            </p>
                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- search form -->
                    <form action="#" method="post" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Buscar...">
                            <span class="input-group-btn">
                                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">MENU DE NAVEGACION</li>
                        <li class="active">
                            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>

                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-user"></i>
                                <span>Usuarios</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Listar</a></li>
                                <li><a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'agregar')); ?>"><i class="fa fa-circle-o"></i> Agregar</a></li>
                            </ul>
                        </li>
                        
                         <li class="treeview">
                            <a href="#">
                                <i class="fa fa-users"></i>
                                <span>Pacientes</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="<?php echo $this->url(array('controller' => 'paciente', 'action' => 'index')); ?>"><i class="fa fa-circle-o"></i> Listar</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Agregar</a></li>
                            </ul>
                        </li>
                         <li class="treeview">
                            <a href="#">
                                <i class="fa fa-user-md"></i>
                                <span>Medicos</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Listar</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Agregar</a></li>
                            </ul>
                        </li>
                        <!--<li class="treeview">
                            <a href="#">
                                <i class="fa fa-stethoscope"></i>
                                <span>Especialidades</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Listar</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Agregar</a></li>
                            </ul>
                        </li>-->
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-flask"></i>
                                <span>Laboratorio</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="<?php echo $this->url(array('controller' => 'laboratorio', 'action' => 'listar')); ?>">
                                    <i class="fa fa-circle-o"></i>Listar Pedidos</a></li>
                                <li><a href="<?php echo $this->url(array('controller' => 'laboratorio', 'action' => 'pedido')); ?>">
                                    <i class="fa fa-circle-o"></i> Realizar Pedido</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-tv"></i>
                                <span>Imagenología</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="#"><i class="fa fa-circle-o"></i>Ver Pedidos</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Realizar Pedido</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-calendar"></i>
                                <span>Agendamiento</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li class="active"><a href="#"><i class="fa fa-circle-o"></i>Ver Agenda</a></li>
                                <li><a href="#"><i class="fa fa-circle-o"></i> Nueva Cita</a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>
                <?php echo $this->layout()->content; ?>
            
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0.0
                </div>
                <strong>&copy;<?php echo date("Y");?><a href="https://adminlte.io"> Juan Perugachi</a> </strong>Todos los derechos reservados. 
            </footer>

            <!-- Control Sidebar -->

            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
                 
            <div class="control-sidebar-bg"></div>
        </div>
        <input type="hidden" name="dir" id="dir" readonly="readonly"  value="<?php echo $this->baseUrl; ?>">
        <!-- jQuery 3 -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/jquery-ui/jquery-ui.min.js"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        <!-- Bootstrap 3.3.7 -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- Morris.js charts -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/raphael/raphael.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/bower_components/morris.js/morris.min.js"></script>
        <!-- Sparkline -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
        <!-- jvectormap -->
        <script src="<?php echo $this->baseUrl; ?>/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <!-- jQuery Knob Chart -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
        <!-- daterangepicker -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/moment/min/moment.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- datepicker -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <!-- DataTables -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src="<?php echo $this->baseUrl; ?>/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
        <!-- Slimscroll -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <!-- FastClick -->
        <script src="<?php echo $this->baseUrl; ?>/bower_components/fastclick/lib/fastclick.js"></script>
        <!-- AdminLTE App -->
        <script src="<?php echo $this->baseUrl; ?>/dist/js/adminlte.min.js"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="<?php echo $this->baseUrl; ?>/dist/js/pages/dashboard.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="<?php echo $this->baseUrl; ?>/dist/js/demo.js"></script>
        <script src="<?php echo $this->baseUrl; ?>/js/laboratorio.js"></script>
        <script>
            $(function () {
              $('#data_table').DataTable()
            })
         </script>
    </body>
</html>
