
<script>
  $(function () {
    $('#tabla_pacientes').DataTable()
  })
</script>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Pacientes
            <small>Listar</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>"><i class="fa fa-dashboard"></i> Home</a></li>
            <li ><a href="#">Pacientes</a></li>
            <li class="active">Listar</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-warning ">
                    <div class="box-header  with-border">
                        <h3 class="box-title">Pacientes Registrados</h3>
                        <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" type="button" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                        </button>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="data_table" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>HC</th>
                                    <th>Nombres</th>
                                    <th>Apellidos</th>
                                    <th>Cedula</th>
                                    <th>Fecha Nacimiento</th>
                                    <th>Sexo</th>
                                    <th>Fecha Creacion</th>
                                    <th>Opcion</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                $table_m = new Application_Model_DbTable_Paciente(); //objeto del modelo historial
                                        $datos = $table_m->listar_pacientes();
                                    foreach ($datos as $item): ?>
                                    <tr>
                                        <td><?php echo $item->hc_digital ?></td>
                                        <td><?php echo $item->primer_nombre ?> <?php echo $item->segundo_nombre ?></td>
                                        <td><?php echo $item->apellido_paterno ?> <?php echo $item->apellido_materno ?></td>
                                        <td><?php echo $item->ci ?></td>
                                        <td><?php echo $item->fecha_nacimiento ?></td>
                                        <td><?php echo $item->sexo ?></td>
                                        <td><?php echo $item->fecha_creacion ?></td>
                                        <td><div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm btn-flat dropdown-toggle" data-toggle="dropdown">
                                        Accion <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu dropdown-default pull-right" role="menu">
                                        <!-- STUDENT PROFILE LINK -->
                                        <li>
                                            <a href="#" onclick=""><i class="fa fa-user-circle"></i>Perfil</a>
                                        </li>
                                        <li>
                                            <a href="#" onclick=""><i class="fa fa-pencil-square"></i>Editar</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="#" onclick=""><i class="fa fa-trash"></i>Eliminar</a>
                                        </li>
                                    </ul>
                                </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>HC</th>
                                    <th>Nombres</th>
                                    <th>Apellidos</th>
                                    <th>Cedula</th>
                                    <th>Fecha Nacimiento</th>
                                    <th>Sexo</th>
                                    <th>Fecha Creacion</th>
                                    <th>Opcion</th>
                                </tr>
                            </tfoot>
                        </table>
                        
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
