<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		 <h1>
			  Laboratorio
			  <small>Realizar Pedido</small>
		 </h1>
		 <ol class="breadcrumb">
			  <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>"><i class="fa fa-dashboard"></i> Home</a></li>
			  <li ><a href="#">Laboratorio</a></li>
			  <li class="active">Realizar Pedido</li>
		 </ol>
	</section>
	<!-- Main content -->
	<section class="content">
		 <div class="row d-flex justify-content-between">

			  <div class="col-sm-6">
					<div class="box box-success ">
						 <div class="box-header with-border">
							  <h3 class="box-title">Datos Demograficos</h3>
							  <div class="box-tools pull-right">
							  <button class="btn btn-box-tool" type="button" data-widget="collapse">
							  <i class="fa fa-minus"></i>
							  </button>
							  </div>
						 </div>
						 <!-- /.box-header -->
						 <div class="box-body">
							  <form role="form">
									<div class="box-body">
										<div class="row">
											
											<div class="col-xs-6">
												 <div class="form-group">
													  <label for="nombre">Numero de archivo</label>
													  <input type="text" class="form-control" id="nombre" placeholder="Ingrese el nombre">
												 </div>
											</div>
											<div class="col-xs-6">
												 <div class="form-group">
													  <label for="apellido">Cedula</label>
													  <input type="text" class="form-control" id="apellido" placeholder="Ingrese el apellido">
												 </div>
											</div>
									  </div>
										 <div class="row">
											  <div class="col-xs-6">
													<div class="form-group">
														 <label for="nombre">Nombres</label>
														 <input type="text" class="form-control" id="nombre" placeholder="Ingrese el nombre">
													</div>
											  </div>
											  <div class="col-xs-6">
													<div class="form-group">
														 <label for="apellido">Apellidos</label>
														 <input type="text" class="form-control" id="apellido" placeholder="Ingrese el apellido">
													</div>
											  </div>
										 </div>
										 <div class="row">
											  <div class="col-xs-6">
													<div class="form-group">
											  <label for="correo">Fecha de nacimiento</label>
											  <input type="email" class="form-control" id="correo" placeholder="Ingrese el correo">
										 </div>
											  </div>
											  <div class="col-xs-6">
													<div class="form-group">
														 <label for="usuario">Edad</label>
														 <input type="text" class="form-control" id="usuario" placeholder="Ingrese el nombre de usuario">
													</div>
											  </div>
										 </div>
										 
									</div>
									<!-- /.box-body -->

									<div class="box-footer">
									</div>
							  </form>

						 </div>
						 <!-- /.box-body -->
					</div>
					<!-- /.box -->
			  </div>
			  <div class="col-sm-6">
				<div class="box box-primary ">
					 <div class="box-header with-border">
						  <h3 class="box-title">Seleccion de turno</h3>
						  <div class="box-tools pull-right">
						  <button class="btn btn-box-tool" type="button" data-widget="collapse">
						  <i class="fa fa-minus"></i>
						  </button>
						  </div>
					 </div>
					 <!-- /.box-header -->
					 <div class="box-body">
						  <form role="form">
								<div class="box-body">
									<div class="row">
										
										<div class="col-xs-12">
											 <div class="form-group">
												  <label for="nombre">Seleccione una fecha</label>
												  <input type="text" class="form-control" id="nombre" placeholder="Ingrese el nombre">
											 </div>
										</div>
										<div class="col-xs-4">
											 <div class="form-group">
												  <label for="apellido">LAboratorio</label>
												  <input type="text" class="form-control" id="apellido" placeholder="Ingrese el apellido">
											 </div>
										</div>
										<div class="col-xs-4">
											<div class="form-group">
												 <label for="nombre">turnos</label>
												 <input type="text" class="form-control" id="nombre" placeholder="Ingrese el nombre">
											</div>
									  </div>
								  </div>
										  
									 
								</div>
								<!-- /.box-body -->

								<div class="box-footer">
								</div>
						  </form>

					 </div>
					 <!-- /.box-body -->
				</div>
				<!-- /.box -->
		  		</div>
		 </div>
		 <div class="row d-flex justify-content-between">

			<div class="col-sm-4">
				 <div class="box box-warning ">
					  <div class="box-header with-border">
							<h3 class="box-title">Busqueda de examen</h3>
							<div class="box-tools pull-right">
							<button class="btn btn-box-tool" type="button" data-widget="collapse">
							<i class="fa fa-minus"></i>
							</button>
							</div>
					  </div>
					  <!-- /.box-header -->
					  <div class="box-body">
							<form role="form">
								 <div class="box-body">
									 <div class="row">
										 
										 <div class="col-xs-12">
											  <div class="form-group">
													<label for="nombre">Examen de laboratorio</label>
													<input type="text" class="form-control" id="nombre" placeholder="Ingrese el nombre">
											  </div>
										 </div>
									</div>
									<div class="row">
										<div class="col-xs-12">
											<ul class="list-group">
												<li class="list-group-item active">Cras justo odio</li>
												<li class="list-group-item">Dapibus ac facilisis in</li>
												<li class="list-group-item">Morbi leo risus</li>
												<li class="list-group-item">Porta ac consectetur ac</li>
												<li class="list-group-item">Vestibulum at eros</li>
											 </ul>
										</div>
									</div>
									  
									  
								 </div>
								 <!-- /.box-body -->

								 <div class="box-footer">
								 </div>
							</form>

					  </div>
					  <!-- /.box-body -->
				 </div>
				 <!-- /.box -->
			</div>
			<div class="col-sm-8">
				<div class="row">
					<div class="box box-danger ">
						<div class="box-header with-border">
							 <h3 class="box-title">Pruebas a realizar </h3>
							 <div class="box-tools pull-right">
								 <button class="btn btn-success btn-sm ">Agregar</button>
								 <div class="btn-group" role="group" aria-label="Basic example">
									 <button class="btn btn-link btn-sm ">Marcar todo</button>
								 <button class="btn btn-link btn-sm ">Desmarcar todo</button>
								 </div>
								 
							 <button class="btn btn-box-tool" type="button" data-widget="collapse">
							 <i class="fa fa-minus"></i>
							 </button>
							 </div>
						</div>
						<!-- /.box-header -->
						<div class="box-body">
							 <form role="form">
								  <div class="box-body">
									  <div class="row">
										  
										  <div class="col-xs-4">
											 <div class="form-check">
												 <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
												 <label class="form-check-label" for="defaultCheck1">
													Prueba 1
												 </label>
											  </div>
										  </div>
										  <div class="col-xs-4">
											 <div class="form-check">
												 <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
												 <label class="form-check-label" for="defaultCheck1">
													 Prueba 2
												 </label>
											  </div>
										  </div>
										  <div class="col-xs-4">
											 <div class="form-check">
												 <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
												 <label class="form-check-label" for="defaultCheck1">
													 Prueba 3
												 </label>
											  </div>
										  </div>
									 </div>
									 <div class="row">
										  
										 <div class="col-xs-4">
											<div class="form-check">
												<input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
												<label class="form-check-label" for="defaultCheck1">
												  Prueba 4
												</label>
											 </div>
										 </div>
										 <div class="col-xs-4">
											<div class="form-check">
												<input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
												<label class="form-check-label" for="defaultCheck1">
													Prueba 5
												</label>
											 </div>
										 </div>
										 <div class="col-xs-4">
											<div class="form-check">
												<input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
												<label class="form-check-label" for="defaultCheck1">
													Prueba n
												</label>
											 </div>
										 </div>
									</div>
										
								  </div>
								  <!-- /.box-body -->
	 
								  <div class="box-footer">
								  </div>
							 </form>
	 
						</div>
						<!-- /.box-body -->
				  </div>
				</div>
				<div class="row">
					<div class="box box-success ">
						<div class="box-header with-border">
							 <h3 class="box-title">Detalle</h3>
							 <div class="box-tools pull-right">
								 
							 <button class="btn btn-box-tool" type="button" data-widget="collapse">
							 <i class="fa fa-minus"></i>
							 </button>
							 </div>
						</div>
						<!-- /.box-header -->
						<div class="box-body">
							 <form role="form">
								  <div class="box-body">
									<div class="row">
										<div class="col-xs-4">
											<ul class="list-group ">
												<li class="list-group-item active">Cras justo odio</li>
												<li class="list-group-item">Dapibus ac facilisis in</li>
												<li class="list-group-item">Morbi leo risus</li>
												<li class="list-group-item">Porta ac consectetur ac</li>
												<li class="list-group-item">Vestibulum at eros</li>
											 </ul>
										</div>
										<div class="col-xs-4">
											<ul class="list-group">
												<li class="list-group-item active">Cras justo odio</li>
												<li class="list-group-item">Dapibus ac facilisis in</li>
												<li class="list-group-item">Morbi leo risus</li>
												<li class="list-group-item">Porta ac consectetur ac</li>
												<li class="list-group-item">Vestibulum at eros</li>
											 </ul>
										</div>
										<div class="col-xs-4">
											<ul class="list-group">
												<li class="list-group-item active">Cras justo odio</li>
												<li class="list-group-item">Dapibus ac facilisis in</li>
												<li class="list-group-item">Morbi leo risus</li>
												<li class="list-group-item">Porta ac consectetur ac</li>
												<li class="list-group-item">Vestibulum at eros</li>
											 </ul>
										</div>
									</div>
										
								  </div>
								  <!-- /.box-body -->
	 
								  <div class="box-footer">
									  <button class="btn btn-success btn-block">Enviar</button>
								  </div>
							 </form>
	 
						</div>
						<!-- /.box-body -->
				  </div>
				</div>
			 
			 <!-- /.box -->
			</div>
	  </div>
	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->
